using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TicTacToe
{
    /// <summary>
    /// Interface to set the difficulty level for the game
    /// </summary>
    public partial class Difficulty : Form
    {
        /// <summary>
        /// Constructor: Initialize the form compnents; generated by IDE
        /// </summary>
        public Difficulty()
        {
            InitializeComponent();
        }

        /// <summary>
        /// When the interface loads, initialize trackbar
        /// </summary>
        private void Difficulty_Load(object sender, EventArgs e)
        {
            // Initialize the trackbar with previous difficulty value from the app settings
            tbDifficulty.Value = Properties.Settings.Default.Difficulty;
        }

        /// <summary>
        /// For high value of diffculty notify player that it might take longer time to finish searching the tree
        /// </summary>
        private void tbDifficulty_change(object sender, EventArgs e)
        {
            if (tbDifficulty.Value == 4)
                lblMessage.Visible = true;
            else
                lblMessage.Visible = false;
        }

        /// <summary>
        /// Update the settings on "save"
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnSave_Click(object sender, EventArgs e)
        {
            // Update app settings for the difficulty
            Properties.Settings.Default.Difficulty = tbDifficulty.Value;
            Properties.Settings.Default.Save();
            this.Close();
        }
    }
}
